<?php 

if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_545901677f8eb',
	'title' => 'Optionen',
	'fields' => array (
		array (
			'key' => 'field_5459016f1e0c1',
			'label' => 'Header Hintergrund',
			'name' => 'header_bg',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_5437e1d073819',
	'title' => 'Profil',
	'fields' => array (
		array (
			'key' => 'field_5437ee1bb9816',
			'label' => 'aufgabe',
			'name' => 'task',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5437ee2ab9817',
			'label' => 'Beschreibung',
			'name' => 'beschreibung',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5437ee38b9818',
			'label' => 'Bild',
			'name' => 'bild',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
		array (
			'key' => 'field_5437efd7aea5b',
			'label' => 'Playlist',
			'name' => 'playlist',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'sub_fields' => array (
				array (
					'key' => 'field_5437efedaea5c',
					'label' => 'Song',
					'name' => 'song',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5437effeaea5d',
					'label' => 'Link',
					'name' => 'link',
					'prefix' => '',
					'type' => 'url',
					'instructions' => 'z.B. Youtube, Vimeo, etc.',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'people',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
));

register_field_group(array (
	'key' => 'group_5437a64839ac0',
	'title' => 'Seiten',
	'fields' => array (
		array (
			'key' => 'field_5437a64aaac79',
			'label' => 'Flexibler Inhalt',
			'name' => 'inhalt',
			'prefix' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'button_label' => 'Eintrag hinzufügen',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '5437a65319162',
					'name' => 'layout',
					'label' => 'Layout',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_5437a6cfaac7c',
							'label' => 'Überschrift',
							'name' => 'überschrift',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5437a6e4aac7d',
							'label' => 'Bild',
							'name' => 'bild',
							'prefix' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'column_width' => '',
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
						array (
							'key' => 'field_5437aaca788f5',
							'label' => '',
							'name' => '',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5437a824298ac',
					'name' => 'embed',
					'label' => 'Embed',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5437a835298ad',
							'label' => 'Beschreibung',
							'name' => 'beschreibung',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5437a692aac7b',
							'label' => 'Embed',
							'name' => 'embed',
							'prefix' => '',
							'type' => 'oembed',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'width' => '',
							'height' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5437a824298ab',
					'name' => '',
					'label' => '',
					'display' => 'row',
					'sub_fields' => array (
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5437a823298aa',
					'name' => '',
					'label' => '',
					'display' => 'row',
					'sub_fields' => array (
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5437a822298a9',
					'name' => '',
					'label' => '',
					'display' => 'row',
					'sub_fields' => array (
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5437a821298a8',
					'name' => '',
					'label' => '',
					'display' => 'row',
					'sub_fields' => array (
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5437a803298a7',
					'name' => 'text',
					'label' => 'Text',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5437a681aac7a',
							'label' => 'Text',
							'name' => 'text',
							'prefix' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'format',
		9 => 'featured_image',
		10 => 'tags',
	),
));

register_field_group(array (
	'key' => 'group_5437a3f4eb0eb',
	'title' => 'Sendung',
	'fields' => array (
		array (
			'key' => 'field_5437a3fdc745c',
			'label' => 'Inhalt',
			'name' => 'content',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_5437a449c745d',
			'label' => 'Zusammenfassung',
			'name' => 'excerpt',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5437a51747aa4',
			'label' => 'Bild',
			'name' => 'bild',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
		array (
			'key' => 'field_5437a52847aa5',
			'label' => 'Links',
			'name' => 'links',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'sub_fields' => array (
				array (
					'key' => 'field_5437a59cb4eb2',
					'label' => 'Linkname',
					'name' => 'linkname',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5437a54147aa6',
					'label' => 'Adresse',
					'name' => 'link-url',
					'prefix' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array (
			'key' => 'field_544a4aabb7ab0',
			'label' => 'Moderation',
			'name' => 'moderation',
			'prefix' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'post_type' => array (
				0 => 'people',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
		),
		array (
			'key' => 'field_544a4be0331a4',
			'label' => 'Redaktion',
			'name' => 'redaktion',
			'prefix' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'post_type' => array (
				0 => 'people',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
		),
		array (
			'key' => 'field_544a4b34b7ab1',
			'label' => 'Sendetermine',
			'name' => 'schedule',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'sub_fields' => array (
				array (
					'key' => 'field_544a4efef1a9d',
					'label' => 'Datum',
					'name' => 'date',
					'prefix' => '',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'display_format' => 'd/m/Y',
					'return_format' => 'd/m/Y',
					'first_day' => 1,
				),
				array (
					'key' => 'field_544a4f1af1a9e',
					'label' => 'Stunde',
					'name' => 'hour',
					'prefix' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => 14,
					'placeholder' => '0-23',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => 23,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_544a4f2cf1a9f',
					'label' => 'Minute',
					'name' => 'minute',
					'prefix' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => 0,
					'placeholder' => '0-50',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => 54,
					'step' => 10,
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'shows',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'comments',
		3 => 'format',
		4 => 'featured_image',
		5 => 'send-trackbacks',
	),
));

register_field_group(array (
	'key' => 'group_5437ac345b9d6',
	'title' => 'Stundenplan',
	'fields' => array (
		array (
			'key' => 'field_5437ac6048998',
			'label' => 'Montag',
			'name' => 'montag',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'sub_fields' => array (
				array (
					'key' => 'field_5437ac7948999',
					'label' => 'Von',
					'name' => 'from',
					'prefix' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5446d14e08ba9',
					'label' => 'Bis',
					'name' => 'to',
					'prefix' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5437e3aac8f7c',
					'label' => 'Link',
					'name' => 'link',
					'prefix' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => 0,
					'taxonomy' => 'show',
					'field_type' => 'select',
					'allow_null' => 0,
					'load_save_terms' => 0,
					'return_format' => 'id',
					'multiple' => 0,
				),
			),
		),
		array (
			'key' => 'field_5446d17d5cece',
			'label' => 'Dienstag',
			'name' => 'montag_kopiere',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'sub_fields' => array (
				array (
					'key' => 'field_5446d17d5cecf',
					'label' => 'Von',
					'name' => 'from',
					'prefix' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5446d17d5ced0',
					'label' => 'Bis',
					'name' => 'to',
					'prefix' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5446d17d5ced1',
					'label' => 'Link',
					'name' => 'link',
					'prefix' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'taxonomy' => 'show',
					'field_type' => 'select',
					'allow_null' => 0,
					'load_save_terms' => 0,
					'return_format' => 'id',
					'multiple' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'program',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
));

endif;